### ISSUE TITLE
Is it possible to run on Windows OS?

### ISSUE THREAD

**Issue by sucof** [renatahodovan/fuzzinator#15]
Hi, renatahodovan, is it possible to run on Windows OS? or not, can you give me some advices for adjusting windows os?
thanks.

**Comment by renatahodovan** [comment]
@sucof The optimistic answer is that every commit is already being checked by AppVeyor CI, so Windows is supported to some extent. The realistic answer is that the test suite contains unit tests only, at least for now, and neither the TUI nor the CLI have been tested to work as a whole. Since development happens on OSX and Linux machines, you will most likely have to experiment yourself if Windows is your target. If you are on Windows 10, then the Ubuntu subsystem has the highest chance to work. On older systems, or if the Ubuntu subsystem is not an option, then cygwin might help (urwid claims to support it, so you may even have TUI), or as a last chance, Windows-native Python might work with CLI.

Should any of the above lead to success, I'd be really glad to hear about it. And if the code needed tweaking, patches in the form of PRs would be much appreciated (so that others can benefit from your efforts).
