### ISSUE TITLE
Question: What is Job Validation doing?

### ISSUE THREAD

**Issue by pmatos** [renatahodovan/fuzzinator#29]
Hi!

Great piece of software - I am evaluating fuzzinator to understand if we can use it as the fuzzing framework of the 32bits port of JSC at Igalia.

I am running into this error:
```
[14:36:55] fuzzinator.ui.cli.cli_listener warning():40	#41: Exception in <fuzzinator.job.validate_job.ValidateJob object at 0x7fd2002b8040>: 'id'
Traceback (most recent call last):
  File "/home/pmatos/dev/fuzzinator/fuzzinator/controller.py", line 415, in _run_job
    for issue in job.run():
  File "/home/pmatos/dev/fuzzinator/fuzzinator/job/validate_job.py", line 29, in run
    _, new_issues = self.validate()
  File "/home/pmatos/dev/fuzzinator/fuzzinator/job/validate_job.py", line 43, in validate
    if issue['id'] == self.issue['id'] and not self.issue.get('invalid'):
KeyError: 'id'
```
 
Also, and probably unrelated this line suspiciously looks like a debug line that should have been removed but never was.
https://github.com/renatahodovan/fuzzinator/blob/ed9df5f8becb3d52f02a3511a4a03a7a314ebb1e/fuzzinator/job/validate_job.py#L42

Do you have any idea what could be triggering the above error?

**Comment by pmatos** [comment]
If I change the code to : 
```
        if issue:
            issue['test'] = self.issue['test']
            if 'id' not in issue:
                print("Whoops, 'id' not in issue\n")
            if 'id' not in self.issue:
                print("Whoops, 'id' not in self.issue\n")
            if 'id' in issue and 'id' in self.issue and issue['id'] == self.issue['id'] and not self.issue.get('invalid'):
                self.db.update_issue_by_oid(self.issue['_id'], issue)
                return True, new_issues

            self.add_issue(issue, new_issues=new_issues)
```

I start getting:
```
Whoops, 'id' not in issue

[14:50:38] fuzzinator.ui.cli.cli_listener on_issue_updated():48	#20: Updated issue '79ceee8440f0e1c8a0ab0ca92d041398' in jsc.
[14:50:38] fuzzinator.ui.cli.cli_listener on_issue_invalidated():51	#20: Invalid issue '79ceee8440f0e1c8a0ab0ca92d041398' in jsc.
[14:50:39] fuzzinator.ui.cli.cli_listener on_job_removed():36	#20: Remove job.
[14:50:39] fuzzinator.ui.cli.cli_listener on_job_activated():33	#21: Activate job.
[14:50:39] fuzzinator.call.subprocess_call SubprocessCall():74	Exception: ReferenceError: Can't find variable: QMMJ4QJJ1MUPHNSRMFJBPF1DKWPV4WAAA4ENQRVHIGNLV89ZH2FVRRUW8XGDXVWXKXLCV635R5TLC2058IZXY77AC65Q12FNTPHV2C8G1737SEWYDOMXQJUK1CSFNL1JUPZYDJA1XEDU7Z5B9DAHX3IKIFAADAUTYEE1MSKP272QGQYESI92IU9CEJYJY33NLQ1W0S7743RMM02RTHFWEEUX3SW
global code@/home/pmatos/dev/jsc32-fuzz/fuzzinator/1138302/test-1138326-140498050285040.js:1:220
```

**Comment by pmatos** [comment]
So, if I look at this line:
https://github.com/renatahodovan/fuzzinator/blob/ed9df5f8becb3d52f02a3511a4a03a7a314ebb1e/fuzzinator/call/subprocess_call.py#L76

there's nothing adding an `id` to the issue dict, therefore I am surprised that an `id` is expected to exist on the validate job call.

By the way, my config atm looks like:
```
[fuzzinator]
work_dir=/home/pmatos/dev/jsc32-fuzz/fuzzinator/{uid}
cost_budget=1

[jsc]
timeout=10000

[sut.jsc]
call=fuzzinator.call.SubprocessCall
call.decorate(0)=fuzzinator.call.FileWriterDecorator
exporter=fuzzinator.exporter.TestExporter

[sut.jsc.call]
command=./WebKitBuild/Release/bin/jsc {test}
timeout=${jsc:timeout}
cwd=/home/pmatos/dev/WebKit

[sut.jsc.call.decorate(0)]
filename=${fuzzinator:work_dir}/test-{uid}.js

[fuzz.jsc-with-random]
sut=jsc
fuzzer=fuzzinator.fuzzer.RandomContent
batch=100

[fuzz.jsc-with-random.fuzzer]
min_length=100
max_length=1000

[sut.jsc.exporter.init]
extension=.js
type=text/plain
```

**Comment by pmatos** [comment]
Although #30 seems to fix the problem, I still don't quite understand why job validation runs? It seems to be just duplicating effort to check that the issue just found still happens.

**Comment by renatahodovan** [comment]
Hi @pmatos!

I'm glad you like Fuzzinator. I'm especially happy that someone from Igalia considers using it. A few years ago, I actively fuzzed browser features implemented by Igalia guys and I really loved it. Unfortunatelly, I've less time for this recently, but I'm really glad that someone is working on it and that Fuzzinator might help. :)

But back to the problem...

First of all, it's "validate job" and not "job validation". Fuzzinator schedules 4 different job types: 

1) *FuzzJob* to manage a traditional fuzz session.
2) *ValidateJob* to check if a failure-inducing test case still reproduces a failure.
3) *ReduceJob* to reduce the test case of a failure.
4) *UpdateJob* to update the SUT (Software Under Testing).

So the purpose of ValidateJob is to check whether a test case still reproduces the original failure it triggered. This job can filter out flaky tests or issues that got fixed in the meantime. The validation can happen at various stages:

1) After a batch of fuzz tests got executed, the found issues are scheduled for reduction. Before such a reduction starts, the issue is validated with a ValidateJob.

2) If an automatic SUT update is scheduled for a SUT, then after every update the reported issues are validated before the next fuzz session.

3) If you use either of the UIs (TUI or WUI) then you can manually trigger a validation job for a choosen issue entry.


The problem you just reported is an actual bug in Fuzzinator. It's caused by an unexpected/rare fuzzing setup where the issue ID generation is completely left to the framework. ValidateJob doesn't handle this scenario well. Regarding the fix you just uploaded, I'll comment on the PR entry.

On the other hand, I encourage you to specify how you like to unify the found issues. The framework's basic setup helps to save all the found issues, but won't help to unify them, since it generates the identifier by hashing the source of the test case. Instead, I suggest to analyze the exit code of JSC or the messages it flushes to stdout or stderr. For JSC target, you don't even need to write its configurations from scratch, since there is a set of publicly available configs on [GitHub](https://github.com/renatahodovan/fuzzinator-configs/tree/master/sut/jsc). Disclaimer: I wrote them 6 months ago and they may need adaptation. To use them, you simply need to create a copy of jsc-sample.ini (e.g., as jsc-custom.ini) and extend it as needed. To run Fuzzinator with random generator you should parameterize it like this:

  ```
  fuzzinator --wui fuzzinator.ini fuzzinator-custom.ini jsc.ini jsc-[gtk|mac].ini jsc-random.ini jsc-custom.ini
  ```

I hope it helps! Don't hesitate to ask if you have any further questions!

**Comment by pmatos** [comment]
@renatahodovan I wanted to also thank you for the really helpful comment you wrote earlier on. It was very useful to understand all parts of the code. Also, I did try to look at the configs for jsc in `fuzzinator-configs` but some would redefine others, using just a few missed some bits so I decided to start from scratch. Now that I spent a couple of days looking at this and after your kind and helpful comments, it's start to make some sense.

Thanks.
