### ISSUE TITLE
Question: Differential Fuzzing with Fuzzinator?

### ISSUE THREAD

**Issue by pmatos** [renatahodovan/fuzzinator#31]
Hi,

I feel that there's no way to achieve differential fuzzing with fuzzinator. Have you thought about this?
The use of this for us would be to run different versions of JSC and check if the console output of the SUT (if it doesn't) crash, is the same as other versions. 

Could you add some comments on this? If not possible at the moment, how hard do you think it would be add this feature?

**Comment by renatahodovan** [comment]
Yes, you are right. Fuzzinator doesn't support differential testing or cross-validation natively, yet. Although the need of such a feature arose multiple times in the past, we only implemented custom (and/or private) solutions for this. So we don't have a general building block for this purpose yet.

The simplest solution to implement this would be to create a variant of SubprocessCall which sends the same test to multiple SUTs/devices and collects and compares the results. At the end, it returns an issue dictionary containing the result of comparisons (or crash logs).

However, this can be more complicated. It depends on your needs. Some questions:

1) How do you compare the result of SUTs? Byte-by-byte? Or all of them must contain some keywords? Or ...?

2) Don't you need some normalization on the outputs of the various SUTs (different JS engines can have different but semantically equivalent outputs)?

3) How do you evaluate if the SUTs give different results? Which one is the failing one? Is any of the SUTs special/designated as reference? Or, if any of the results differ, do we manually investigate all of them?

I CC @rerobika since he worked on such a solution to cross-validate JerryScript and nodejs, so he has up-to-date experience in this topic.

**Comment by rerobika** [comment]
Hi @pmatos!

Let me describe how I resolved the cross-validation problem with Fuzzinator. In my scenario the cross-validation target was JerryScript with V8(node) and I used Grammarinator with a custom JS grammar file to generate testcases. 

First of all consider the basic fuzzing approach: The Fuzzinator triggers Grammarinator to generate testcases which are going to be passed for the SUT(JSC in your case) while any kind of failure is constantly monitored.
Since Fuzzinator supports only one SUT simultaneously to resolve the cross-validation problem we need to replace the SUT in the approach above. 
I've created a python script which takes the Grammarinator output as it's input and passes this test to the engines.
This script is connected to the `command` options in the Fuzzinator configs like:
`command=python3 /path/to/validator.py {test}`

After that all the further work is depends on your creativity or the language element/feature you would like to fuzz.
The only remaining problem needs the be solved that validate that both engines gives the same output. 
According to my experience the comparing the outputs byte-to-byte is profitable. The only difficulty is enforce the engines to produce the same output format (at this point some language knowledge is definitely required)  

You can see a validator script that I've used for RegExp validation below. You can freely reuse or get inspiration from it.

```python
#!/usr/bin/env python3
import sys
import random
import string
from subprocess import run, PIPE

def randomString(stringLength=20):
    letters = list(string.ascii_lowercase + string.digits + string.ascii_uppercase)
    return ''.join(random.choice(letters) for i in range(stringLength))

def runTC(engine, regexp, match_string, logger=""):
    tc = "{0}(JSON.stringify(\"{1}\".match({2}), (k,v) => (typeof v == 'string') ? escape(v) : v))".format(logger, match_string, regexp)
    p = run(engine, stdout=PIPE, stderr=PIPE, input=tc, encoding='utf-8')

    return (p.stdout.strip('\r\n'), p.stderr, p.returncode, tc)

def validate(test):
    with open(test, "r+") as file:
        regexp = file.read().strip('\r\n')

    rand_string = randomString()
    jerry_res, jerry_err, jerry_exit, jerry_tc = runTC(["/path/to/jerry", "--no-prompt"], regexp, rand_string)
    node_res, node_err, node_exit, node_tc = runTC("node", regexp, rand_string, 'console.log')

    exit_code = 0

    if jerry_exit != 0:
        if jerry_exit == 1:
            if node_exit != 1:
                exit_code = 1
        else:
            exit_code = 2
    elif jerry_res != node_res:
        exit_code = 3

    if exit_code != 0:
        ex = """
JerryScript:
 - command: {0}
 - Output:{1}
 - ExitCode:{2}
 - stderr:{3}
Node.JS:
 - command: {4}
 - Output:{5}
 - ExitCode:{6}
 - stderr:{7}
"""
        print(ex.format(jerry_tc, jerry_res, jerry_exit, jerry_err, node_tc, node_res, node_exit, node_err), file=sys.stderr)
        sys.exit(exit_code)

validate(sys.argv[1])
```

If you still have any remaining questions about this topic feel free to contact me.

**Comment by pmatos** [comment]
@rerobika Thanks for the helpful comment. It certainly seems like your suggestion would work in my case as well. I will start with something like your suggest and develop it further throughout next year given that fuzzing is a long term goal for us.

Closing the issue as this is now answered.
