### ISSUE TITLE
Deal with maximum issue title size

### ISSUE THREAD

**Issue by pmatos** [renatahodovan/fuzzinator#35]
https://github.com/renatahodovan/fuzzinator/blob/37520f6051e7364f481515a4d325a75a778353d7/fuzzinator/tracker/gitlab.py#L29

In Gitlab maximum issue title size is 256, so I am seeing that when we create an issue with a long title - which could be the assertion failure message, the issue is just not reported at all. Pressing report does nothing to it. My suggestion here is to trim the title to 256, and check the result of the issue create to see if creation was successful because at the moment there's no failure message when something goes wrong.

I will look into this if nobody else has time.

**Comment by pmatos** [comment]
Just noticed that the error shows up in the logs:
```
fuzzer_1  | Traceback (most recent call last):
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/tornado/web.py", line 1702, in _execute
fuzzer_1  |     result = method(*self.path_args, **self.path_kwargs)
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/ui/wui/api_handlers.py", line 223, in post
fuzzer_1  |     self._db.update_issue_by_oid(issue_oid, {'reported': tracker.report_issue(**self.get_content())['url']})
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/fuzzinator/tracker/gitlab.py", line 27, in report_issue
fuzzer_1  |     new_issue = self.project.issues.create(dict(title=title, description=body))
fuzzer_1  |   File "/jscfuzz/venv/lib/python3.7/site-packages/gitlab/exceptions.py", line 289, in wrapped_f
fuzzer_1  |     raise error(e.error_message, e.response_code, e.response_body) from e
fuzzer_1  | gitlab.exceptions.GitlabCreateError: 400: {'title': ['is too long (maximum is 255 characters)']}
```

**Comment by renatahodovan** [comment]
Hi @pmatos !

Thanks for the report. Not giving any feedback about the failure of a report operation is indeed a shortcoming of the current system. I've started to look into how to implement this missing feature.

As per the exact use case about the length limit of the Gitlab tracker, I'm not sure whether it's useful to hard-wire the length of 255 since it might differ between various Gitlab instances or versions. My suggestion is to update the formatter config of your Gitlab tracker by truncating the length of the `short` description (which will be used to fill the default title of the report). E.g., if you use the "official" JSC config from here:

https://github.com/renatahodovan/fuzzinator-configs/blob/master/sut/jsc/jsc.ini#L211

then you should replace this line

```ini
short={{error_type}} {{condition}} in {{function}}
```

with this:

```ini
short={{"%s %s in %s"|format(error_type, condition, function)|truncate(255)}}
```

With an extra boolean attribute of the `truncate` filter you can even ensure not cutting any words in half but keeping only whole words and maybe appending an ellipsis sign.
Documentation: https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.truncate
